apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: default # đổi namespace nếu cần
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:class} \[%{DATA:method}:%{DATA:line}\]" }
      }
      date {
        match => [ "timestamp", "ISO8601" ]
        timezone => "+07:00"
        target => "@timestamp"
      }
      ruby {
        code => "event.set('indexDay', event.get('[@timestamp]').time.localtime('+07:00').strftime('%Y%m%d'))"
      }
    }

    output {
      elasticsearch {
        hosts => ["10.152.183.175:9200"]
        template => "/usr/share/logstash/templates/logstash.template.json"
        template_name => "logstash"
        template_overwrite => true
        index => "logstash-%{indexDay}"
        codec => json
      }
      stdout {
        codec => rubydebug
      }
    }
  
  logstash.template.json: |
    {
      "template": "logstash",
      "index_patterns": ["logstash-*"],
      "settings": {
        "number_of_shards": 1
      },
      "mappings": {
        "_source": {
          "enabled": true
        },
        "properties": {
          "timestamp": {
            "type": "date"
          },
          "loglevel": {
            "type": "keyword"
          },
          "class": {
            "type": "keyword"
          },
          "method": {
            "type": "keyword"
          },
          "line": {
            "type": "keyword"
          }
        }
      }
    }
