apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.16.2
        resources:
          limits:
            memory: 200Mi
        volumeMounts:
        - name: log-volume
          mountPath: /logs
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: log-volume
        hostPath:
          path: path_to/sample/log
      - name: filebeat-config
        configMap:
          name: filebeat-config

---

apiVersion: v1
kind: Service
metadata:
  name: filebeat-service
spec:
  selector:
    app: filebeat
  ports:
    - protocol: TCP
      port: 5045
      targetPort: 5045
  type: ClusterIP
